### ISSUE TITLE
How to read file from azure

### ISSUE THREAD

**Issue by smartaquarius10** [UiPath/Orchestrator-CredentialStorePlugins#4]
In the plugin I'm using Random pass generator. I have kept a text file in wwwroot, bin and plugins folder still unable to locate it. By default, the current directory of orchestrator is C:\Windows\System32.

I have tried through HTTPContext as well but the dll is in .net standard and this object is available in .net framework. Kindly suggest some procedure to read the file through it.

**Comment by cosminvlad** [comment]
Could you post some sample code, so we can better understand what you are trying to do?
